language: php
sudo: false
php:
  - "nightly"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
env:
  - DISABLE_FUNCTIONS=
  - DISABLE_FUNCTIONS="gzopen"
matrix:
  fast_finish: true
  allow_failures:
    - php: "nightly"
services:
  - mysql
  - postgresql
notifications:
  irc:
    channels:
        - "chat.freenode.net#dokuwiki"
    on_success: change
    on_failure: change
install:
  - php _test/fetchphpunit.php
before_script:
  - test -z "$DISABLE_FUNCTIONS" || echo "disable_functions=$DISABLE_FUNCTIONS" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp _test/mysql.conf.php.dist _test/mysql.conf.php
  - cp _test/pgsql.conf.php.dist _test/pgsql.conf.php
  - ./_test/phpunit.phar --version
script:
  - cd _test && ./phpunit.phar --verbose --stderr
